services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=carlosalmeida
      - MYSQL_PASSWORD=
    networks:
      - infrastructure
    volumes:
      - ./containerdata/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-server
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - infrastructure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always

  nginxproxymanager:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - infrastructure
    volumes:
      - ./containerdata/nginx:/data
      - ./containerdata/letsencrypt:/etc/letsencrypt

  giteaserver:
    image: gitea/gitea:latest
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql-server:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=
    restart: always
    networks:
      - infrastructure
    volumes:
      - ./containerdata/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mysql
    security_opt:
      - no-new-privileges:true
      
volumes:
  portainer_data:

networks:
  infrastructure:
    name: infrastructure-network